{{- if not .Values.database.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaosblade-space-exploration.fullname" . }}-database
  namespace: {{ .Values.namespace | default "chaosblade" }}
  labels:
    {{- include "chaosblade-space-exploration.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-secret
type: Opaque
data:
  username: {{ (.Values.database.username | default "root") | b64enc }}
  password: {{ (.Values.database.password | default "password") | b64enc }}
{{- end }}

{{- if not .Values.redis.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaosblade-space-exploration.fullname" . }}-redis
  namespace: {{ .Values.namespace | default "chaosblade" }}
  labels:
    {{- include "chaosblade-space-exploration.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-secret
type: Opaque
data:
  password: {{ (.Values.redis.password | default "redis123") | b64enc }}
{{- end }}

{{- if not .Values.kubernetes.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaosblade-space-exploration.fullname" . }}-kubernetes
  namespace: {{ .Values.namespace | default "chaosblade" }}
  labels:
    {{- include "chaosblade-space-exploration.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubernetes-secret
type: Opaque
data:
  token: {{ (.Values.kubernetes.token | default "dummy-token") | b64enc }}
{{- end }}

{{- if not .Values.llm.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaosblade-space-exploration.fullname" . }}-llm
  namespace: {{ .Values.namespace | default "chaosblade" }}
  labels:
    {{- include "chaosblade-space-exploration.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-secret
type: Opaque
data:
  key: {{ (.Values.llm.api.key | default "dummy-key") | b64enc }}
{{- end }}
