{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chaosblade-space-exploration.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "chaosblade" }}
  labels:
    {{- include "chaosblade-space-exploration.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
