version: '3.9'
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chaosblade
    ports:
      - "3306:3306"
    volumes:
      - ./local/mysql-init:/docker-entrypoint-initdb.d
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  redis:
    image: redis:7
    ports:
      - "6379:6379"

