server:
  port: 8101
spring:
  application:
    name: svc-task-resource
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spaceexploration?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: non-null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.chaosblade: DEBUG
    org.springframework.web: DEBUG

# External topology service endpoints
external:
  topology:
    base-url: ${EXTERNAL_TOPOLOGY_BASE_URL:http://localhost:8106}
    timeout-ms: 15000

endpoints:
  executor-base-url: ${EXECUTOR_BASE_URL:http://localhost:8102}

llm:
  api:
    url: ${LLM_API_URL:https://api.siliconflow.cn/v1/chat/completions}
    key: ${LLM_API_KEY:}
    model: ${LLM_API_MODEL:Qwen/QwQ-32B}
  timeout:
    ms: 500000
  retries: 3
