server:
  port: 8105

spring:
  application:
    name: svc-reqrsp-proxy
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spaceexploration?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non-null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Kubernetes configuration
kubernetes:
  api-url: ${K8S_API_URL:https://127.0.0.1:6443}
  token: ${K8S_TOKEN:}
  verify-ssl: ${K8S_VERIFY_SSL:false}

# Recording configuration
recording:
  envoy:
    image: envoyproxy/envoy:v1.28.3
    port: 15006
    admin-port: 9901
    tap-dir: /var/log/envoy/taps
    max-buffered-bytes: 2097152
  default-duration-sec: 600
  auto-collect-interval-sec: 30

# Logging configuration
logging:
  level:
    com.chaosblade.svc.reqrspproxy: INFO
    io.fabric8.kubernetes: INFO
    org.springframework.data.redis: INFO
  file:
    name: app.log  # 输出到当前目录的app.log文件
    # 或者指定完整路径
    # name: /var/log/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB    # 单个文件最大大小
      max-history: 30        # 保留30个历史文件
      total-size-cap: 1GB    # 总大小限制