FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY gen/ gen/
COPY inventory-svc/ inventory-svc/

RUN CGO_ENABLED=0 go build -o /inventory-svc ./inventory-svc

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /inventory-svc /inventory-svc
ENTRYPOINT ["/inventory-svc"]
