apiVersion: v2
name: chaosblade-space-exploration
description: A Helm chart for ChaosBlade Space Exploration microservices
type: application
version: 1.0.0
appVersion: "1.0.0-SNAPSHOT"
keywords:
  - chaos-engineering
  - microservices
  - spring-boot
  - kubernetes
home: https://github.com/chaosblade-io/chaosblade-space-exploration
sources:
  - https://github.com/chaosblade-io/chaosblade-space-exploration
maintainers:
  - name: ChaosBlade Team
    email: chaosblade@linux.alibaba.com
# dependencies:
#   - name: mysql
#     version: "9.4.0"
#     repository: "https://charts.bitnami.com/bitnami"
#     condition: mysql.enabled
#   - name: redis
#     version: "22.0.7"
#     repository: "https://charts.bitnami.com/bitnami"
#     condition: redis.enabled
